### ISSUE TITLE
native audio input + FFT analysis

### ISSUE THREAD

**Issue by birkschmithuesen** [birkschmithuesen/SpeculativeAI_Interspace#1]
right now the audio input and FFT is done by another Software (Ableton Live) and send via OSC. 
See def fft_handler

Here is an example for fft in Python:
https://www.toptal.com/algorithms/shazam-it-music-processing-fingerprinting-and-recognition

features:

- Use microphone as input for now.
- Ability to set FPS
- optionally send FFT data with adress format /fft_train 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.  to port 8001
- implement bin distribution that is adapted to human ear if it makes sense (logarithmic? do research!) see linked article

**Comment by kryptokommunist** [comment]
Also incorporate mic livel correction into the fft: https://makersportal.com/blog/2018/9/17/audio-processing-in-python-part-ii-exploring-windowing-sound-pressure-levels-and-a-weighting-using-an-iphone-x

Consider adding a von Hann window to minimise artefacts resulting from chunking: https://en.wikipedia.org/wiki/Hann_function
